language: node_js
services:
- mongodb
- redis-server
node_js:
- '0.10'
script:
  - npm test
  - npm run-script lint
env:
  global:
  - PROVIDER_URL="http://localhost:8000"
  - ANYFETCH_API_ID="not-used"
  - ANYFETCH_API_SECRET="not-used"
  - secure: DEvHGv/fQPjCLT2JquQ3hjGj+gsul8kzywmJ7T+FKLgbCEGdbvBUERouL8d77EBMHGIHSjn9o5wQmHrDwA72QVNaDp1vFm2SMY4FVyCxSgv4TbFtXd2Mh9LMAIQzx5U02z8GbynTe1vsfqkI7qh2eNInI1MfRNvPCkYGHg5heFw=
  - secure: GRiH8j50YGqzcj1XqZifPmiWbSWJBXZqIutSNn8xXSfT1Kq4cHP4h8jdNN+d3Cct0AX7KUAVlnyvdYgpSwTzpObgzhEbp/ViCA28FSus1+58b0ftVPU7ajN+atP5lNuovKgEflOBIpNnK9gVH2auIdZxEOSsmCyZeeOE6w82LpI=
  - secure: HjaA7rm6IZ2yPglFOeq/RECkiUe8xnRMNO5Ija2ltYktslbD1Vtx3sXnt6F83mv3oYEAmZD2ifnk6FEmiLfoBWzQN/u099hXPeOTtrkptkjKyZjjHu+RpQpohJ4tb1RJYuDI7YikSqrTkHQ4y0Ti3Dle7Dak5ZaYBmrq9RDZeDA=
