language: node_js
services: 
  - mongodb
  - redis-server
node_js:
- '0.10'
before_script: npm install --dev
script: npm test
env:
  global:
  - PROVIDER_URL="http://localhost:8000"
  - GCONTACTS_ANYFETCH_ID="not-used"
  - GCONTACTS_ANYFETCH_SECRET="not-used"
  - secure: AAkhYBNVVY9iSmedw3lY4pYBfs7SfADp1LOFeIRqTTiVz/LhUqKYVbHSWPu4Sp5w5T+7vHcOqsEt4VHx5Fh055HFPGx/5ljVprW7dae2kDO4yAJuAb4NZzh0xLcvlPFRkiNKw/Wex8W1sCWJ5mxAcC2lbIwHjRi1kTMjgfzrkbw=
  - secure: B/suIgnuxmvd2SifyJh9DxIJXBjM/CWMDsj4lPkBczcjP3kyNzmSrQnEdeALIZdnmLzn1+KWCoG5XbZAZzdE6M2cH0sE3js65jSIKXTlAm/Qix1fTTgLHl1IJKHnaEMg62YfDbGx7vrbTTLcg+r/eRqKWnryY2PEtwzUTWTmoVc=
  - secure: bEo5kkn1BAh0M47+vld3gsxvL0z/oDCeWucp8/YzSpOdk9KDM95oLxv+oWP0ZNQWCSk8Z/KLlJwAQr1oPjBJEdKuzSG+V0xt81CQWgLhOZlJgZZB+8sXg2z4sQ8mge9IEijKzViq8XKlL66DwOq3NeSDGOLSaZU5hD9ixmX0bbY=
